#!/usr/bin/env node

var Narcissus = require('narcissus/main');
var _ = require('underscore');
var child_process = require('child_process');
var fs = require('fs');
var path = require('path');

var jsgrep = require('./lib/jsgrep.js');

var config = {
  paths: [ ],
  recursive: false,
  patchFile: false,
  sedMode: false,
  asJavascript: false
};

function usage(hasError) {
  if (hasError) {
    console.log("See jspatch --help for usage information.");
    process.exit(hasError ? 1 : 0);
  }
  console.log("jspatch: JavaScript source code refactoring tool");
  console.log("");
  console.log("Usage: jspatch [OPTIONS] PATCHFILE FILES...");
  console.log("");
  console.log("Options:");
  console.log("  -f, --patch-script=FILE   Path to patch script.");
  console.log("  -J, --javascript          Interpret PATCHFILE as a match script.");
  console.log("  -e, --expression=SCRIPT   Sed mode. SCRIPT is in the form of s/A/B/");
  console.log("  -r, --recursive           Scan directories for JavaScript files.");
  process.exit(0);
}

(function parseArgs() {
  var getopt = require('node-getopt');
  var parser = new getopt.BasicParser(
    'f:(match-script)J(javascript)e:(expression)r(recursive)_(help)',
    process.argv);

  while ((option = parser.getopt()) !== undefined) {
    switch(option.option) {
      case 'f':
        config.patchFile = option.optarg;
        break;
      case 'J':
        config.asJavascript = true;
        break;
      case 'e':
        config.sedMode = option.optarg;
        break;
      case 'r':
        config.recursive = true;
        break;
      case '?':
      case '_':
        usage(option.error);
        break;
    }
  }

  config.paths = process.argv.slice(parser.optind());

  if (!config.patchFile && !config.sedMode) {
    if (config.paths.length > 0) {
      config.patchFile = config.paths.shift();
    } else {
      console.error("jspatch: Must specify a patch file.");
      usage(true);
    }
  }
})();

var paths = config.paths;
var matchFn;

function processPatch(patchSource) {
  var lines = patchSource.split('\n');

  var i = 0;
  var chunks = [];

  function processChunk() {
    var chunk = { top: [], find: [], replace: [] };
    var inReplacement = false;

    for(; i < lines.length; i++) {
      if (lines[i] == '---') {
        break;
      } else if (lines[i][0] == '-') {
        if (!inReplacement) {
          if (chunk.find.length > 0) {
            // XXX: due to the way I compile the patch, each replacement would be
            // independent of one another, which would be confusing.
            console.error('jspatch: Only 1 replacement is permitted per chunk.');
            process.exit(1);
          }
          inReplacement = true;
          chunk.top.push('A_jspatchAutovar');
        }
        chunk.find.push(lines[i].substr(1));

      } else if (lines[i][0] == '+') {
        if (!inReplacement) {
          console.error(
            'jspatch: Insertions are not yet supported, only replacements.');
          process.exit(1);
        }
        chunk.replace.push(lines[i].substr(1));

      } else {
        if (inReplacement) {
          if (chunk.replace.length == 0) {
            console.error(
              'jspatch: Removals are not yet supported, only replacements.');
            process.exit(1);
          }
          inReplacement = false;
        }
        chunk.top.push(lines[i]);
      }
    }

    chunk.top = chunk.top.join('\n');
    chunk.find = chunk.find.join('\n');
    chunk.replace = chunk.replace.join('\n');

    chunks.push(chunk);
  }

  while (i < lines.length) {
    processChunk();
  }

  function generateMatchFn(chunks) {
    return function(jsgrep) {
      _.each(chunks, function(chunk) {
        jsgrep.find(chunk.top, function(vars) {
          vars.A_jspatchAutovar.match(chunk.find, function(vars) {
            vars.node.replaceWith(chunk.replace);
          });
        });
      });
    };
  }

  return generateMatchFn(chunks);
}

function generateDiff(oldFilename, newFile, callback) {
  var tempFilename, tries = 1;
  do {
    tempFilename = path.join(process.env.TEMP || "/tmp",
      "jspatch." + path.basename(oldFilename, ".js") +
      (tries == 1 ? "" : ("." + tries)) + ".js");
    tries++;
  } while (path.existsSync(tempFilename));

  var tempFile = fs.openSync(tempFilename, 'w');
  try {
    fs.writeSync(tempFile, newFile);
  } finally {
    fs.closeSync(tempFile);
  }

  var child =
    child_process.spawn('diff', [ '-u', oldFilename, tempFilename ]);

  child.stdout.on('data', function(data) {
    process.stdout.write(data);
  });
  child.stderr.on('data', function(data) {
    process.stderr.write(data);
  });

  child.on('exit', function(code) {
    fs.unlinkSync(tempFilename);
    if (code !== 0 && code !== 1) {
      // diff returns 0 for no differences, 1 for differences, 2 for error
      console.error('jspatch: diff exited with code ' + code);
      process.exit(1);
    }
    callback();
  });
}

function doFile(filename, callback) {
  var source = fs.readFileSync(filename).toString();
  // If the first character is a shebang, comment it out
  if (source.substr(0, 2) == '#!') {
    source = "//" + source;
  }

  try {
    var ast = Narcissus.parser.parse(source, filename, 1);
  } catch(e) {
    console.warn(e.name + ": " + e.message);
    return callback();
  }

  try {
    jsgrep.jsgrep({
      source: ast,
      matchScript: matchFn,
      callback: function(node, variables) {
      }
    });
  } catch(e) {
    if (!(e instanceof Error) && e.message) {
      console.error("jspatch: " + e.message);
      process.exit(1);
    }
    throw e;
  }

  var modifiedSource = ast.tokenizer.source;

  // Try to parse the modified source
  try {
    Narcissus.parser.parse(modifiedSource, 'modified source', 1);
  } catch(e) {
    console.log('jspatch: ' + filename +
      ': warning: modifications resulted in an invalid JavaScript file!');
    console.log('This is probably a bug in jspatch. ' +
      'Please let ry@fb.com know!');
  }

  if (source.substr(0, 4) == '//#!') {
    // Now remove the comment from the shebang
    source = source.substr(2);
    modifiedSource = modifiedSource.substr(2);
  }

  generateDiff(filename, modifiedSource, callback);
}

function queueDirectory(directory) {
  if (!config.recursive) {
    return;
  }
  var files = fs.readdirSync(directory);
  for (var i = 0; i < files.length; i++) {
    var filePath = path.join(directory, files[i]);
    var stat = fs.statSync(filePath);
    if (stat.isDirectory() ||
        filePath.substr(-3) == ".js") {
      paths.push(filePath);
    }
  }
}

function jspatch_loop() {
  if (paths.length == 0) {
    return;
  }

  var nextPath = paths.shift();
  var stat = fs.statSync(nextPath);
  if (stat.isDirectory()) {
    queueDirectory(nextPath);
    return jspatch_loop();
  } else {
    doFile(nextPath, jspatch_loop);
  }
}

if (config.sedMode) {
  // XXX hurr hurr can't sed mode division, paths in string literals, blah blah
  var sedMode = config.sedMode.split('/');
  if (sedMode.length != 4 || sedMode[0] != 's' || sedMode[3] != '') {
    console.error('jspatch: Pattern for sed mode must be in the form of ' +
      '"s/search/replace/".');
    process.exit(1);
  }
  matchFn = function(jsgrep) {
    jsgrep.replaceAll(sedMode[1], sedMode[2]);
  };
} else if (config.asJavascript) {
  matchFn = config.patchFile;
} else {
  var patchSource = fs.readFileSync(config.patchFile).toString();
  matchFn = processPatch(patchSource);
}

jspatch_loop();

// vim: ft=javascript
